### ISSUE TITLE
Create release of the main branch

### ISSUE THREAD

**Issue by ZeynepDYilmaz** [ZeynepDYilmaz/swe573-Project#59]
(taken from the moodle announcement)
Create a release of your software using the tag & release feature of your repository. The tag version should be v0.9 and the message should be: Swe573 2021 Fall -  Final Project Report - Your Name. Write anything relevant to your release notes. The release should be of master/main branch. This means that you should merge all software you want to be assessed into the main branch. Do not delete other branches to preserve the approach to work.

Create a zip file including your release and report and name it Swe573 2021 Fall- FinalProjectReport-Your Name.zip

**Comment by ZDenizYStenhaug** [comment]
the release can be reached here: https://github.com/ZeynepDYilmaz/swe573-Project/releases/tag/v.0.0.9
